language: python
python: 3.6.1

matrix:
  fast_finish: true


dist: trusty
sudo: required

cache:
  timeout: 43200 # 12 hours
  pip: true


install: pip install -r requirements.txt

script:
  py.test
